import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { MenuProvider } from "@/Context/MenuContext";
import Navigation from "@/Components/Navigation/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description:
    "Generated by create next apExplore a professional portfolio website/application crafted with Next.js and Tailwind CSS. This meticulously designed platform showcases a range of projects, seamlessly integrating responsive design principles for optimal viewing across devices. Leveraging libraries like react-icons, react-scroll, framer-motion, and react-intersection-observer, this portfolio offers a dynamic user experience with smooth animations and interactive elements. Discover the culmination of skill, creativity, and innovation in this showcase of accomplishments.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MenuProvider>
          <Suspense fallback={<div>Loading ...</div>}>
            <div className="h-screen w-screen border-2 border-red-700 flex">
              <div>
                <Navigation />
              </div>
              <div>{children}</div>
            </div>
          </Suspense>
        </MenuProvider>
      </body>
    </html>
  );
}
